### Create a new medical profile entity
#POST http://localhost:8081/medical-profiles
POST http://lb-2edf77c4.elb.localhost.localstack.cloud:8084/api/medical-profiles
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Priti Test3",
  "email": "pritiTest3@example.com",
  "address": "809 north3 street",
  "dateOfBirth": "1996-07-08",
  "registeredDate": "2024-05-04"
}
###
