### Create a new medical profile entity
POST http://localhost:8081/medical-profiles
Content-Type: application/json

{
  "name": "Yia Seeds",
  "email": "yia@example.com",
  "address": "109 north street",
  "dateOfBirth": "1999-07-08",
  "registeredDate": "2025-06-04"
}
###
