server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://host.docker.internal:8085
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: medical-profile-service-route
          uri: http://host.docker.internal:8081
          predicates:
            - Path=/api/medical-profiles/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: api-docs-medical-profile-route
          uri: http://host.docker.internal:8081
          predicates:
            - Path=/api-docs/medical-profiles
          filters:
            - RewritePath=/api-docs/medical-profiles,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://host.docker.internal:8085
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs








