### Update medical profile
PUT http://localhost:8081/medical-profiles/6fb8b130-0696-44e9-a23e-83a93602c076
Content-Type: application/json

{
  "name": "Sia Seeds Updated",
  "email": "siaupdated@example.com",
  "address": "609 north street",
  "dateOfBirth": "1994-07-08"
}
###